name: quest-chess-game # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Chess Tactics Quest
summary: Master chess strategies through missions.
description: Improve your chess game with scenario-based puzzles, real-time matches, and in-depth analysis to take your skills to the next level.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  quest-chess-game:
    command: bin/quest-chess-game-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  quest-chess-game:
    plugin: dump
    source: .
    organize:
      quest-chess-game-bin: bin/
